# Generated by Django 4.2.7 on 2026-01-08 13:05

import django.core.validators
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='ملفات PDF أو صور (JPG, PNG, GIF) - أقصى حجم 10MB', upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('view', 'مشاهدة'), ('download', 'تحميل'), ('print', 'طباعة'), ('delete', 'حذف'), ('upload', 'رفع')], max_length=20, verbose_name='الإجراء'),
        ),
    ]
